### ISSUE TITLE
how to solve cannot read property 'children' of null error in detailModel?

### ISSUE THREAD

**Issue by ruchabhutada** [paramquery/grid#95]
I m using row detail hierarchy. but i m not getting detail model display. I have written var colM and separately declaring var data to it. And in dataModel, i added  'data: data', . Similarly, I have added var childData for gridDetailModel and put 'data:childData' into it. and if I write location: remote or local in both the places, it only shows main grid and not the detailModel. But, if I write type:"detail" in colM, it gives an error, says cannot read property 'children' of null. Remaining is everything ok in code.I have verified from "http://paramquery.com/demos/detail" this. Actually I m not getting "ui-icon-triangle-1-e"  this symbol in main grid so that I can expand it to see it detail grid. I m working on this from last 5days. Please help me.

**Comment by ruchabhutada** [comment]
Can you please tell me how to resolve this ?
Where am I wrong?

**Comment by paramquery** [comment]
Is it possible for you to share a jsfiddle. http://jsfiddle.net/pb5kpred/

**Comment by ruchabhutada** [comment]
plz check : http://jsfiddle.net/ruchabhutada/pb5kpred/2/

**Comment by ruchabhutada** [comment]
??

**Comment by ruchabhutada** [comment]
can you reply me? I have posted it on jsfiddle as u said
my work is stopped because of this.

**Comment by karan-chauhan** [comment]
Did you solve this issue?

**Comment by paramquery** [comment]
It's resolved in v2.4.1

**Comment by ruchabhutada** [comment]
Hello sir,
Thank you for your kind reply. I have not solved this issue. I will check that. Thank you..!
